Version 0.1.1
Audi-Project/Virus-Test-RoundingCat pull request #21
Opened 2023-06-09 13:10 UTC by TaeWooKim-SCH

2023-06-09 13:41 UTC, R-jisu reviewed
Main, Loading 코드리뷰 완료

2023-06-09 13:41 UTC, R-jisu commented on src/App.jsx
> +        <Route path="/loading" element={<Loading />} />
이상한 루트 입력했을 때 대체할 방법이 필요할 것 같아요. '*'에 Main으로 이동한다거나 그런 부분이 추가되면 좋을 것 같습니다.

2023-06-09 13:41 UTC, R-jisu commented on src/components/button/Button.jsx
>    bg-[#8152F1]
버튼 bg 색은 여러번 쓰이는 걸로 알고 있으니 tailwind.config.js에 명시해서 사용하는게 좋을 것 같아요!
혹시 이 버튼이 그냥 재사용된다면 버튼이름을 StartButton말고 포괄적인 이름으로 바꾸는게 좋을 것 같습니다/

2023-06-09 13:41 UTC, R-jisu commented on src/pages/Result-styles.jsx
> +
이 파일은 pages보다 styles라는 파일을 하나 파서 그 파일 아래에 두는게 더 좋을 것 같습니다! page파일에는 실제 page컴포넌트들만 있는게 좋을 것 같아요.

2023-06-09 13:41 UTC, R-jisu commented on src/pages/Loading.jsx
> +    <div className="flex items-center w-[390px] h-[844px] bg-[#D8C5FD]">
bg 색도 tailwind.config.js에 명시하는게 좋을 것 같습니다.

2023-06-09 13:50 UTC, plla2 commented on src/components/result/modal/Modal.jsx
> +                key={d.id}
d.id d.url 이런거보단 d가 확실한 어떤 데이터인지 써주면 좋을 것 같습니다!

2023-06-09 13:50 UTC, plla2 commented on src/components/result/modal/Modal.jsx
> +          <img className="inline absolute bottom-1.5 left-9" src={closeBtn} alt="버튼 제목" />
일관성있게 인라인 스타일보다는 styled-components를 주는게 좋을 것 같습니다.

2023-06-09 15:45 UTC, Jiwonp12 commented on src/pages/Result-styles.jsx
> +export const Box2 = tw.div`
box2는 없어도 되지않을까용?

2023-06-09 15:50 UTC, Jiwonp12 commented on src/pages/Result.jsx
> +      templateId: 94563,
메인과 결과 템플릿이 다르면 더 좋을것 같아용

2023-06-10 07:45 UTC, seobi-97 commented on src/pages/Result-styles.jsx
> +export const Box2 = tw.div`
box2가 없어도 큰 차이는 없습니다.
두 개의 영역(box,box2)를 만들어 가운데 정렬만 해서 보이는 위치만 살짝 다릅니다.

2023-06-10 07:45 UTC, seobi-97 commented on src/pages/Result-styles.jsx
> +export const Box2 = tw.div`
> box2는 없어도 되지않을까용?
box2가 없어도 큰 차이는 없습니다.
두 개의 영역(box,box2)를 만들어 가운데 정렬만 해서 보이는 위치만 살짝 다릅니다.

2023-06-10 07:46 UTC, seobi-97 commented
Main 브랜치로 이동

2023-06-10 07:47 UTC, seobi-97 requested changes
Main브랜치로 merge

2023-06-10 07:51 UTC, seobi-97 reviewed
merge

2023-06-13 13:37 UTC, closed without merging